# Template used for Kubernetes manifest
# https://spacelift.io/blog/kubernetes-deployment-yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: world-service
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: world-service
  template:
    metadata:
      labels:
        app: world-service
    spec:
      containers:
      - name: world-service
        image: eric02pham/world-service
        ports:
        - containerPort: 8081
  
